spring:
  application:
    name: cloud.cachecloud-web.open
    import: classpath:spring/spring.xml
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
server:
  port: 8080
  domain: 127.0.0.1:8080

cachecloud:
  primary:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/cachecloud-open?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&connectTimeout=3000&socketTimeout=10000&serverTimezone=Asia/Shanghai
    username: cachecloud-open
    password: cachecloud-open
    minimumIdle: 10
    maximumPoolSize: 50
  redis: #配置cachecloud-web需要的redis，用户存储任务流log
    enable: true #if config redis, suggest config true
    main:
      host: 127.0.0.1
      port: 6379
      password:
  web:
    clients: 127.0.0.1
aof:
  rewrite:
    ignore-appIds: